services:
  server:
    env_file: .env
    build: ./server
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./server:/app
    depends_on:
      - db
    command: ./wait-for db:3306 -t 30 -- go run .

  client:
    env_file: .env
    build: ./client
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:/app

  db:
    image: mysql:8.0.30-oracle
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: setup
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
