services:
  server:
    env_file: .env
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
  client:
    env_file: .env
    build: ./client
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
