services:
  server:
    env_file: .env
    build: ./server
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./server:/app
    depends_on:
      - db
    command: ./wait-for db:3306 -t 30 -- go run .

  client:
    env_file: .env
    build: ./client
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:/app

  db:
    image: mysql:8.0.30-oracle
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
